import re
import subprocess
from pathlib import Path
from docx import Document
from lxml import etree
import copy

def process_latex_to_omml(text):
    """Takes a string with latex, returns list of w:p elements generated by pandoc."""
    Path("temp.md").write_text(text, encoding="utf-8")
    subprocess.run(["pandoc", "temp.md", "-o", "temp.docx"], check=True, capture_output=True)
    doc = Document("temp.docx")
    return [p._element for p in doc.paragraphs]

def fix_document(docx_path, out_path):
    doc = Document(docx_path)
    
    # 1. Fix Math Equations
    # Iterate over all paragraphs
    for para in doc.paragraphs:
        text = para.text
        # If the paragraph contains math delimiters
        if '$' in text:
            # We want to preserve the original paragraph properties (style, alignment, etc.)
            original_pPr = para._element.find('.//{http://schemas.openxmlformats.org/wordprocessingml/2006/main}pPr')
            if original_pPr is not None:
                original_pPr = copy.deepcopy(original_pPr)
            
            # Generate new paragraph elements from pandoc
            new_elements = process_latex_to_omml(text)
            
            if new_elements:
                # Replace the original paragraph with the first generated one
                parent = para._element.getparent()
                index = parent.index(para._element)
                
                # We can insert multiple paragraphs if pandoc generated multiple (e.g. lists or line breaks)
                for i, new_el in enumerate(new_elements):
                    # inject original properties into the first paragraph at least
                    if i == 0 and original_pPr is not None:
                        new_pPr = new_el.find('.//{http://schemas.openxmlformats.org/wordprocessingml/2006/main}pPr')
                        if new_pPr is not None:
                            new_el.replace(new_pPr, copy.deepcopy(original_pPr))
                        else:
                            new_el.insert(0, copy.deepcopy(original_pPr))
                            
                    parent.insert(index + i, copy.deepcopy(new_el))
                    
                # Remove the original paragraph
                parent.remove(para._element)
    
    # 2. Fix Page Numbers
    NSMAP = {
        'w': 'http://schemas.openxmlformats.org/wordprocessingml/2006/main',
    }
    
    # Check where Chapter 1 starts
    chapter_1_idx = -1
    for i, para in enumerate(doc.paragraphs):
        if 'Chapter 1' in para.text or ('Introduction' in para.text and para.style.name.startswith('Heading')):
            chapter_1_idx = i
            break
            
    # Setup sections
    if len(doc.sections) == 1 and chapter_1_idx != -1:
        # Create a section break right before Chapter 1
        para = doc.paragraphs[chapter_1_idx]
        pPr = para._element.get_or_add_pPr()
        sectPr = etree.SubElement(pPr, f'{{{NSMAP["w"]}}}sectPr')
        
        # Section 0 (Front matter) - Roman
        sect_front = doc.sections[0]._sectPr
        pgNumType_front = etree.SubElement(sect_front, f'{{{NSMAP["w"]}}}pgNumType')
        pgNumType_front.set(f'{{{NSMAP["w"]}}}fmt', 'lowerRoman')
        pgNumType_front.set(f'{{{NSMAP["w"]}}}start', '1')
        
        # Section 1 (Main content) - Arabic
        pgNumType_main = etree.SubElement(sectPr, f'{{{NSMAP["w"]}}}pgNumType')
        pgNumType_main.set(f'{{{NSMAP["w"]}}}fmt', 'decimal')
        pgNumType_main.set(f'{{{NSMAP["w"]}}}start', '1')
        
        # Add footers with page numbers
        add_page_number_to_footer(doc.sections[0])
        add_page_number_to_footer(doc.sections[1])

    elif len(doc.sections) > 1:
        # Fix existing sections
        sect_front = doc.sections[0]._sectPr
        pgNumType_front = sect_front.find(f'{{{NSMAP["w"]}}}pgNumType')
        if pgNumType_front is None:
            pgNumType_front = etree.SubElement(sect_front, f'{{{NSMAP["w"]}}}pgNumType')
        pgNumType_front.set(f'{{{NSMAP["w"]}}}fmt', 'lowerRoman')
        pgNumType_front.set(f'{{{NSMAP["w"]}}}start', '1')
        
        sect_main = doc.sections[1]._sectPr
        pgNumType_main = sect_main.find(f'{{{NSMAP["w"]}}}pgNumType')
        if pgNumType_main is None:
            pgNumType_main = etree.SubElement(sect_main, f'{{{NSMAP["w"]}}}pgNumType')
        pgNumType_main.set(f'{{{NSMAP["w"]}}}fmt', 'decimal')
        pgNumType_main.set(f'{{{NSMAP["w"]}}}start', '1')
        
        add_page_number_to_footer(doc.sections[0])
        add_page_number_to_footer(doc.sections[1])

    # 3. Center Block Diagrams / Images
    for para in doc.paragraphs:
        # if paragraph has an inline drawing (image)
        if para._element.findall('.//{http://schemas.openxmlformats.org/wordprocessingml/2006/main}drawing'):
            para.alignment = 1  # WD_ALIGN_PARAGRAPH.CENTER

    doc.save(out_path)

def add_page_number_to_footer(section):
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.shared import Pt
    footer = section.footer
    footer.is_linked_to_previous = False
    for p in footer.paragraphs:
        p.clear()
    para = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
    para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = para.add_run()
    run.font.name = 'Times New Roman'
    run.font.size = Pt(10)
    
    NSMAP_W = 'http://schemas.openxmlformats.org/wordprocessingml/2006/main'
    fldChar_begin = etree.SubElement(run._element, f'{{{NSMAP_W}}}fldChar')
    fldChar_begin.set(f'{{{NSMAP_W}}}fldCharType', 'begin')
    run2 = para.add_run()
    instrText = etree.SubElement(run2._element, f'{{{NSMAP_W}}}instrText')
    instrText.set('{http://www.w3.org/XML/1998/namespace}space', 'preserve')
    instrText.text = ' PAGE '
    run3 = para.add_run()
    fldChar_end = etree.SubElement(run3._element, f'{{{NSMAP_W}}}fldChar')
    fldChar_end.set(f'{{{NSMAP_W}}}fldCharType', 'end')

if __name__ == "__main__":
    src = "Banana_Spoilage_Detection_Report_p.docx"
    dst = "Banana_Spoilage_Detection_Report_Final.docx"
    print("Fixing document in place...")
    fix_document(src, dst)
    print(f"Saved to {dst}")
